name: Service-J
on:
  push:
   branches:
     - master
   paths:
      - 'service-name.json'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "${{ ENDPOINT }}"
        user: "admin"
        token: ${{ Jenkins-Token }}
        job: "service" 
